name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        run: npm run tauri build

      - name: Ensure Finder permissions
        run: |
          osascript -e 'tell application "Finder" to activate'
          sleep 2

      - name: Package Build Artifacts
        run: |
          mkdir -p dist
          cp -R src-tauri/target/release/bundle/macos/xgm-manager.app dist/
          cp -R src-tauri/target/release/bundle/share/create-dmg dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: tauri-build
          path: ./downloaded-artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./downloaded-artifacts/**/*.{dmg,exe,AppImage}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
