name: Build & Release Tauri App

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            targets: [ 'universal-apple-darwin' ]
          - platform: windows-latest
            targets: [ 'x86_64-pc-windows-msvc' ]
          - platform: ubuntu-latest
            targets: [ 'x86_64-unknown-linux-gnu' ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18 (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        # 确保 @tauri/cli 被安装
        run: npm ci

      - name: Publish Tauri App
        # 这一步会调用 node_modules/.bin/tauri
        uses: tauri-apps/tauri-action@v0.5
        with:
          runner: 'npm'
          workingDirectory: '.'
          targets: ${{ toJson(matrix.targets) }}
          release: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
