name: 'Publish Tauri App'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Setup Node.js (with Yarn cache)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Rust crates
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Extract version (Unix)
        if: runner.os != 'Windows'
        id: version_unix
        shell: bash
        run: |
          version=$(grep '"version":' src-tauri/tauri.conf.json | head -1 | cut -d '"' -f4)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Extract version (Windows)
        if: runner.os == 'Windows'
        id: version_win
        shell: pwsh
        run: |
          $content = Get-Content src-tauri/tauri.conf.json -Raw
          $json = $content | ConvertFrom-Json
          echo "version=$($json.version)" >> $env:GITHUB_OUTPUT

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0.5
        with:
          runner: 'yarn'
          workingDirectory: '.'
          args: ${{ matrix.args }}
          release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: app-v${{ steps.version_unix.outputs.version || steps.version_win.outputs.version }}
          name: "App v${{ steps.version_unix.outputs.version || steps.version_win.outputs.version }}"
          body: "See the assets to download this version and install."
          draft: true
          prerelease: false
          files: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.app
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
